version: '3.8'
services:
  inventory-service:
    build: ../inventory-service
    ports:
      - "8001:8001"
    depends_on:
      - mongo_inventory
    environment:
      - MONGO_URI=mongodb://root:example@mongodb_inventory_service:27017
      - DATABASE_NAME=inventory
      - SERVER_ADDRESS=:8001
      - ENABLE_AUTH=true
      - API_USERNAME=your_username,admin
      - API_PASSWORD=your_password
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=3600
    networks:
      - backend

  order-service:
    build: ../order-service
    ports:
      - "8003:8003"
    depends_on:
      - mongo_order
    environment:
      - MONGO_URI=mongodb://root:example@mongodb_order_service:27017
      - DATABASE_NAME=orders
      - SERVER_ADDRESS=:8003
      - ENABLE_AUTH=true
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=3600
    networks:
      - backend

  api-gateway:
    build: .
    ports:
      - "8002:8002"
    environment:
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - inventory-service
    volumes:
      - ./tls/cert.pem:/tls/cert.pem
      - ./tls/key.pem:/tls/key.pem
    networks:
      - backend

  mongo_inventory:
    image: mongo
    container_name: mongodb_inventory_service
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-inventory-data:/data/db
    command: mongod --bind_ip_all
    networks:
      - backend


  mongo_order:
    image: mongo
    container_name: mongodb_order_service
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      -  mongo-order-data:/data/db
    command: mongod --bind_ip_all
    networks:
      - backend

volumes:
    mongo-inventory-data:
    mongo-order-data:

networks:
  backend: